baseURL: http://example.org/
languageCode: en-us
title: JOEY
theme: PaperMod


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: English
    contentDir: content/english
    weight: 1
  fr:
    languageName: Français
    contentDir: content/french
    weight: 2



languages:
  en:
    params:
      profileMode:
        enabled: true
        title: "<Do Not Go Gentle Into That Good Night>" # optional default will be site title
        subtitle: "Do Not Go Gentle Into That Good Night"

label:
  text: "Home"
  icon: /apple-touch-icon.png
  iconHeight: 35              

menu:
  main:
    - identifier: home
      name: 主页
      url: /
      weight: 1 # 重量越轻，就越往前面排，“1”则是置顶
    - identifier: search
      name: 搜索
      url: /search/
      weight: 2 # 重量越轻，就越往前面排，“1”则是置顶
    - identifier: archives
      name: 时间轴
      url: /archives/
      weight: 3
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    - identifier: about
      name: about me
      url: about
      weight: 30
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    # description: "这是一个纯粹的博客......"
    author: Joey
    # author: ["Me", "You"] # multiple authors
    defaultTheme: auto  # defaultTheme: light or  dark 
    disableThemeToggle: false
    DateFormat: "2006-01-02"
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecialistPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    hideFooter: false # 隐藏页脚
    ShowWordCounts: true
    VisitCount: true

    ShowLastMod: true #显示文章更新时间

    ShowToc: true # 显示目录
    TocOpen: true # 自动展开目录

    comments: true
    


outputs:
  home:
    - HTML
    - RSS
    - JSON 
